### ISSUE TITLE
你好，下载数据的链接失效了，您有下载好的数据吗？

### ISSUE THREAD

**Issue by wangjiaod** [yxliwhu/NYUD-FCN8s#1]

**Comment by yxliwhu** [comment]
@wangjiaod You could download here. [https://connectpolyu.sharepoint.com/:u:/s/GRP_Share_others/EQK0tiS1EO5IiUUJqNabGJgBaZosucO5GkJgEpdOpQ90tw?e=cp9ovL](url)

**Comment by wangjiaod** [comment]
您好，这个在github上打不开，复制链接到浏览器出现的是微软账号登录

**Comment by yxliwhu** [comment]
@wangjiaod You could try this link [https://connectpolyu-my.sharepoint.com/:u:/g/personal/16902456r_connect_polyu_hk/EWYGHmk4jltMijbgcsNVtrsB6FF0y4hQxx8j3jCa7wb7vg?e=SQ4cO3](url)
